/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5TradeOrderAlgoPostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 必填<br>交易模式<br>保证金模式：`isolated`：逐仓 ；`cross`<br>全仓非保证金模式：`cash`：非保证金
    #[serde(rename = "tdMode")]
    pub td_mode: String,
    /// 必填<br>订单方向。买：`buy` 卖：`sell`
    #[serde(rename = "side")]
    pub side: String,
    /// 必填<br>订单类型。<br>`conditional`：单向止盈止损<br>`oco`：双向止盈止损<br>`trigger`：计划委托<br>`iceberg`：冰山委托<br>`twap`：时间加权委托
    #[serde(rename = "ordType")]
    pub ord_type: String,
    /// 必填<br>委托数量
    #[serde(rename = "sz")]
    pub sz: String,
    /// 订单标签<br>字母（区分大小写）与数字的组合，可以是纯字母、纯数字，且长度在1-16位之间
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// 可选<br>持仓方向<br>在双向持仓模式下必填，且仅可选择 `long` 或 `short`
    #[serde(rename = "posSide", skip_serializing_if = "Option::is_none")]
    pub pos_side: Option<String>,
    /// 非必填<br>保证金币种，如：USDT<br>仅适用于单币种保证金模式下的全仓杠杆订单
    #[serde(rename = "ccy", skip_serializing_if = "Option::is_none")]
    pub ccy: Option<String>,
    /// 非必填<br>是否只减仓，`true` 或 `false`，默认`false`<br>仅适用于币币杠杆订单
    #[serde(rename = "reduceOnly", skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// 非必填<br>市价单委托数量的类型<br>交易货币：`base_ccy`<br>计价货币：`quote_ccy`<br>仅适用于币币订单
    #[serde(rename = "tgtCcy", skip_serializing_if = "Option::is_none")]
    pub tgt_ccy: Option<String>,
    /// 非必填<br>止盈触发价，如果填写此参数，必须填写止盈委托价<br>适用于`止盈止损委托`
    #[serde(rename = "tpTriggerPx", skip_serializing_if = "Option::is_none")]
    pub tp_trigger_px: Option<String>,
    /// 非必填<br>止盈委托价，如果填写此参数，必须填写止盈触发价<br>委托价格为-1时，执行市价止盈<br>适用于`止盈止损委托`
    #[serde(rename = "tpOrdPx", skip_serializing_if = "Option::is_none")]
    pub tp_ord_px: Option<String>,
    /// 非必填<br>止损触发价，如果填写此参数，必须填写止损委托价<br>适用于`止盈止损委托`
    #[serde(rename = "slTriggerPx", skip_serializing_if = "Option::is_none")]
    pub sl_trigger_px: Option<String>,
    /// 非必填<br>止损委托价，如果填写此参数，必须填写止损触发价<br>委托价格为-1时，执行市价止损<br>适用于`止盈止损委托`
    #[serde(rename = "slOrdPx", skip_serializing_if = "Option::is_none")]
    pub sl_ord_px: Option<String>,
    /// 非必填<br>计划委托触发价格<br>适用于`计划委托`
    #[serde(rename = "triggerPx", skip_serializing_if = "Option::is_none")]
    pub trigger_px: Option<String>,
    /// 非必填<br>委托价格<br>委托价格为-1时，执行市价委托<br>适用于`计划委托`
    #[serde(rename = "orderPx", skip_serializing_if = "Option::is_none")]
    pub order_px: Option<String>,
    /// 非必填<br>距离盘口的比例<br>pxVar和pxSpread只能传入一个<br>适用于`冰山委托`和`时间加权委托`
    #[serde(rename = "pxVar", skip_serializing_if = "Option::is_none")]
    pub px_var: Option<String>,
    /// 非必填<br>距离盘口的比例价距<br>适用于`冰山委托`和`时间加权委托`
    #[serde(rename = "pxSpread", skip_serializing_if = "Option::is_none")]
    pub px_spread: Option<String>,
    /// 非必填<br>单笔数量<br>适用于`冰山委托`和`时间加权委托`
    #[serde(rename = "szLimit", skip_serializing_if = "Option::is_none")]
    pub sz_limit: Option<String>,
    /// 非必填<br>挂单限制价<br>适用于`冰山委托`和`时间加权委托`
    #[serde(rename = "pxLimit", skip_serializing_if = "Option::is_none")]
    pub px_limit: Option<String>,
    /// 非必填<br>挂单限制价<br>适用于`时间加权委托`
    #[serde(rename = "timeInterval", skip_serializing_if = "Option::is_none")]
    pub time_interval: Option<String>,
}

impl ApiV5TradeOrderAlgoPostRequest {
    pub fn new(inst_id: String, td_mode: String, side: String, ord_type: String, sz: String) -> ApiV5TradeOrderAlgoPostRequest {
        ApiV5TradeOrderAlgoPostRequest {
            inst_id,
            td_mode,
            side,
            ord_type,
            sz,
            tag: None,
            pos_side: None,
            ccy: None,
            reduce_only: None,
            tgt_ccy: None,
            tp_trigger_px: None,
            tp_ord_px: None,
            sl_trigger_px: None,
            sl_ord_px: None,
            trigger_px: None,
            order_px: None,
            px_var: None,
            px_spread: None,
            sz_limit: None,
            px_limit: None,
            time_interval: None,
        }
    }
}

