/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5TradeCancelAlgosPostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 必填<br>策略委托单ID
    #[serde(rename = "algoId")]
    pub algo_id: String,
}

impl ApiV5TradeCancelAlgosPostRequest {
    pub fn new(inst_id: String, algo_id: String) -> ApiV5TradeCancelAlgosPostRequest {
        ApiV5TradeCancelAlgosPostRequest {
            inst_id,
            algo_id,
        }
    }
}

