/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5TradeCancelOrderPostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 可选<br>订单ID， ordId和clOrdId必须传一个，若传两个，以ordId为主。
    #[serde(rename = "ordId", skip_serializing_if = "Option::is_none")]
    pub ord_id: Option<String>,
    /// 可选<br>客户自定义订单ID<br>字母（区分大小写）与数字的组合，可以是纯字母、纯数字且长度要在1-32位之间。
    #[serde(rename = "clOrdId", skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
}

impl ApiV5TradeCancelOrderPostRequest {
    pub fn new(inst_id: String) -> ApiV5TradeCancelOrderPostRequest {
        ApiV5TradeCancelOrderPostRequest {
            inst_id,
            ord_id: None,
            cl_ord_id: None,
        }
    }
}

