/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5TradeClosePositionPostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT-SWAP`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 必填<br>保证金模式。全仓：`cross`；逐仓：`isolated`
    #[serde(rename = "mgnMode")]
    pub mgn_mode: String,
    /// 可选<br>持仓方向<br>单向持仓模式下：可不填写此参数，默认值`net`，如果填写，仅可以填写`net`<br>双向持仓模式下： 必须填写此参数，且仅可以填写 `long`：平多 ，`short`：平空
    #[serde(rename = "posSide", skip_serializing_if = "Option::is_none")]
    pub pos_side: Option<String>,
    /// 可选<br>保证金币种，如：`USDT`。单币种保证金模式的全仓币币杠杆平仓必填
    #[serde(rename = "ccy", skip_serializing_if = "Option::is_none")]
    pub ccy: Option<String>,
    /// 否<br>当市价全平时，平仓单是否需要自动撤销,默认为false.`false`：不自动撤单 `true`：自动撤单
    #[serde(rename = "autoCxl", skip_serializing_if = "Option::is_none")]
    pub auto_cxl: Option<bool>,
}

impl ApiV5TradeClosePositionPostRequest {
    pub fn new(inst_id: String, mgn_mode: String) -> ApiV5TradeClosePositionPostRequest {
        ApiV5TradeClosePositionPostRequest {
            inst_id,
            mgn_mode,
            pos_side: None,
            ccy: None,
            auto_cxl: None,
        }
    }
}

