/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5TradeAmendOrderPostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 可选<br>订单ID， ordId和clOrdId必须传一个，若传两个，以ordId为主。
    #[serde(rename = "ordId", skip_serializing_if = "Option::is_none")]
    pub ord_id: Option<String>,
    /// 可选<br>客户自定义订单ID<br>字母（区分大小写）与数字的组合，可以是纯字母、纯数字且长度要在1-32位之间。
    #[serde(rename = "clOrdId", skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// 可选<br>修改的新数量，newSz和newPx不可同时为空。对于部分成交订单，该数量应包含已成交数量。
    #[serde(rename = "newSz", skip_serializing_if = "Option::is_none")]
    pub new_sz: Option<String>,
    /// 可选<br>修改的新价格
    #[serde(rename = "newPx", skip_serializing_if = "Option::is_none")]
    pub new_px: Option<String>,
    /// 非必填<br>`false`：不自动撤单 `true`：自动撤单 当订单修改失败时，该订单是否需要自动撤销。默认为`false`
    #[serde(rename = "cxlOnFail", skip_serializing_if = "Option::is_none")]
    pub cxl_on_fail: Option<bool>,
    /// 非必填<br>用户自定义修改事件ID，字母（区分大小写）与数字的组合，可以是纯字母、纯数字且长度要在1-32位之间。
    #[serde(rename = "reqId", skip_serializing_if = "Option::is_none")]
    pub req_id: Option<String>,
}

impl ApiV5TradeAmendOrderPostRequest {
    pub fn new(inst_id: String) -> ApiV5TradeAmendOrderPostRequest {
        ApiV5TradeAmendOrderPostRequest {
            inst_id,
            ord_id: None,
            cl_ord_id: None,
            new_sz: None,
            new_px: None,
            cxl_on_fail: None,
            req_id: None,
        }
    }
}

