/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: v5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5AccountSetIsolatedModePostRequest {
    /// 逐仓保证金划转模式<br>`automatic`：开仓自动划转，`autonomy`：自主划转
    #[serde(rename = "isoMode")]
    pub iso_mode: String,
    /// 业务线类型<br>`MARGIN`：币币杠杆，`CONTRACTS`：合约
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ApiV5AccountSetIsolatedModePostRequest {
    pub fn new(iso_mode: String) -> ApiV5AccountSetIsolatedModePostRequest {
        ApiV5AccountSetIsolatedModePostRequest {
            iso_mode,
            r#type: None,
        }
    }
}

