/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: v5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5AccountSetLeveragePostRequest {
    /// 必填<br>杠杆倍数
    #[serde(rename = "lever")]
    pub lever: String,
    /// 保证金模式<br>`isolated`：逐仓，`cross`：全仓<br>如果`ccy`有效传值，该参数值只能为`cross`。
    #[serde(rename = "mgnMode")]
    pub mgn_mode: String,
    /// 可选<br>产品ID：币对、合约<br>`instId`和`ccy`至少要传一个；如果两个都传，默认使用instId
    #[serde(rename = "instId", skip_serializing_if = "Option::is_none")]
    pub inst_id: Option<String>,
    /// 可选<br>保证金币种，仅适用于跨币种保证金模式的全仓`币币杠杆`。
    #[serde(rename = "ccy", skip_serializing_if = "Option::is_none")]
    pub ccy: Option<String>,
    /// 可选<br>持仓方向<br>`long`：双向持仓多头<br>`short`：双向持仓空头<br>`net`：单向持仓<br>在双向持仓且保证金模式为逐仓条件下必填，且仅可选择`long`或`short`，其他情况下非必填，默认`net`；仅适用于`交割/永续`
    #[serde(rename = "posSide", skip_serializing_if = "Option::is_none")]
    pub pos_side: Option<String>,
}

impl ApiV5AccountSetLeveragePostRequest {
    pub fn new(lever: String, mgn_mode: String) -> ApiV5AccountSetLeveragePostRequest {
        ApiV5AccountSetLeveragePostRequest {
            lever,
            mgn_mode,
            inst_id: None,
            ccy: None,
            pos_side: None,
        }
    }
}

