/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: v5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5AccountPositionMarginBalancePostRequest {
    /// 必填<br>产品ID，如：`BTC-USDT-SWAP`
    #[serde(rename = "instId")]
    pub inst_id: String,
    /// 必填<br>持仓方向，默认值是`net`<br>`long`：双向持仓多头<br>`short`：双向持仓空头<br>`net`：单向持仓
    #[serde(rename = "posSide")]
    pub pos_side: String,
    /// 必填<br>增加/减少保证金<br>`add`：增加 `reduce`：减少
    #[serde(rename = "type")]
    pub r#type: String,
    /// 增加或减少的保证金的币种<br>仅适用于逐仓自主划转保证金模式下的币币杠杆
    #[serde(rename = "ccy", skip_serializing_if = "Option::is_none")]
    pub ccy: Option<String>,
    /// 是否自动借币 true 或 false<br>仅适用于逐仓自主划转保证金模式下的币币杠杆
    #[serde(rename = "auto", skip_serializing_if = "Option::is_none")]
    pub auto: Option<String>,
    /// 是否支持`跨币种保证金模式`下的借币转出/转入默认为`false`。
    #[serde(rename = "loanTrans", skip_serializing_if = "Option::is_none")]
    pub loan_trans: Option<bool>,
}

impl ApiV5AccountPositionMarginBalancePostRequest {
    pub fn new(inst_id: String, pos_side: String, r#type: String) -> ApiV5AccountPositionMarginBalancePostRequest {
        ApiV5AccountPositionMarginBalancePostRequest {
            inst_id,
            pos_side,
            r#type,
            ccy: None,
            auto: None,
            loan_trans: None,
        }
    }
}

