/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqExecuteQuotePostRequest {
    /// 询价单ID. 
    #[serde(rename = "rfqId")]
    pub rfq_id: String,
    /// 报价单ID.
    #[serde(rename = "quoteId")]
    pub quote_id: String,
    /// 用于部分执行的腿的数量。腿的数量比例必须与原RFQ相同。注意：每条腿的tgtCcy和side和原RFQ一致，px和对应Quote一致。
    #[serde(rename = "legs", skip_serializing_if = "Option::is_none")]
    pub legs: Option<Legs>,
}

impl ApiV5RfqExecuteQuotePostRequest {
    pub fn new(rfq_id: String, quote_id: String) -> ApiV5RfqExecuteQuotePostRequest {
        ApiV5RfqExecuteQuotePostRequest {
            rfq_id,
            quote_id,
            legs: None,
        }
    }
}


#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Legs {
    inst_id: String,

    td_mode: String,

    ccy: String,

    sz: String,

    side: String,

    pos_side: String,

    tgt_ccy: String,
}
