/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqCreateQuotePostRequest {
    /// 询价单ID.
    #[serde(rename = "rfqId")]
    pub rfq_id: Vec<String>,
    /// 报价单自定义ID
    #[serde(rename = "clQuoteId", skip_serializing_if = "Option::is_none")]
    pub cl_quote_id: Option<bool>,
    /// 询价单方向， buy 或者 sell
    #[serde(rename = "quoteSide")]
    pub quote_side: String,
    /// 组合交易 
    #[serde(rename = "legs")]
    pub legs: Vec<String>,
}

impl ApiV5RfqCreateQuotePostRequest {
    pub fn new(rfq_id: Vec<String>, quote_side: String, legs: Vec<String>) -> ApiV5RfqCreateQuotePostRequest {
        ApiV5RfqCreateQuotePostRequest {
            rfq_id,
            cl_quote_id: None,
            quote_side,
            legs,
        }
    }
}

