/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqMakerInstrumentSettingsPostRequest {
    /// 产品类别，枚举值包括 FUTURES, OPTION, SWAP 和 SPOT。
    #[serde(rename = "instType")]
    pub inst_type: String,
    /// 是否接收该instType下所有产品。有效值为true或false。默认false。
    #[serde(rename = "includeAll", skip_serializing_if = "Option::is_none")]
    pub include_all: Option<bool>,
    /// instType的元素
    #[serde(rename = "data")]
    pub data: InsTypes,
}

impl ApiV5RfqMakerInstrumentSettingsPostRequest {
    pub fn new(inst_type: String, data: InsTypes) -> ApiV5RfqMakerInstrumentSettingsPostRequest {
        ApiV5RfqMakerInstrumentSettingsPostRequest {
            inst_type,
            include_all: None,
            data,
        }
    }
}


#[derive(Serialize, Deserialize,Debug,PartialEq,Clone,Default)]
#[serde(rename_all = "camelCase")]
pub struct InsTypes {
    uly: Option<String>,

    max_block_sz: Option<String>,

    maker_px_band: Option<String>,

    inst_id: Option<String>,
}
