/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqCancelBatchQuotesPostRequest {
    /// 可选<br>用户自定义报价单ID列表
    #[serde(rename = "clQuoteIds")]
    pub cl_quote_ids: Vec<String>,
    /// 可选<br>报价单ID列表
    #[serde(rename = "quoteIds")]
    pub quote_ids: Vec<String>,
}

impl ApiV5RfqCancelBatchQuotesPostRequest {
    pub fn new(cl_quote_ids: Vec<String>, quote_ids: Vec<String>) -> ApiV5RfqCancelBatchQuotesPostRequest {
        ApiV5RfqCancelBatchQuotesPostRequest {
            cl_quote_ids,
            quote_ids,
        }
    }
}

