/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqCreateRfqPostRequest {
    /// 报价方列表。
    #[serde(rename = "counterparties")]
    pub counterparties: Vec<String>,
    /// 是否匿名询价，true表示匿名询价，false表示公开询价，默认值为 false，为true时，即使在交易执行之后，身份也不会透露给报价方。
    #[serde(rename = "anonymous", skip_serializing_if = "Option::is_none")]
    pub anonymous: Option<bool>,
    /// 询价单自定义ID，字母（区分大小写）与数字的组合，可以是纯字母、纯数字且长度要在1-32位之间。
    #[serde(rename = "clRfqId", skip_serializing_if = "Option::is_none")]
    pub cl_rfq_id: Option<String>,
    /// RFQ是否可以被部分执行，如果腿的比例和原RFQ一致。有效值为true或false。默认为false。
    #[serde(rename = "allowPartialExecution", skip_serializing_if = "Option::is_none")]
    pub allow_partial_execution: Option<bool>,
    /// 组合交易，每次最多可以提交15组交易信息
    #[serde(rename = "legs")]
    pub legs: Vec<String>,
}

impl ApiV5RfqCreateRfqPostRequest {
    pub fn new(counterparties: Vec<String>, legs: Vec<String>) -> ApiV5RfqCreateRfqPostRequest {
        ApiV5RfqCreateRfqPostRequest {
            counterparties,
            anonymous: None,
            cl_rfq_id: None,
            allow_partial_execution: None,
            legs,
        }
    }
}

