/*
 * REST API
 *
 * # 使用说明   <b>该功能接口用户需先登陆，接口只会请求模拟环境</b><br><br>*Parameters* 面板中点击`Try it out`按钮，编辑请求参数，点击`Execute`按钮发送请求。*Responses* 面板中查看请求结果。<br>
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV5RfqCancelQuotePostRequest {
    /// 可选<br>报价单ID.
    #[serde(rename = "quoteId")]
    pub quote_id: String,
    /// 可选<br>用户自定义报价单ID.. 
    #[serde(rename = "clQuoteId")]
    pub cl_quote_id: String,
}

impl ApiV5RfqCancelQuotePostRequest {
    pub fn new(quote_id: String, cl_quote_id: String) -> ApiV5RfqCancelQuotePostRequest {
        ApiV5RfqCancelQuotePostRequest {
            quote_id,
            cl_quote_id,
        }
    }
}

